export {default as image1} from '../assest/image1.png'
export {default as image2} from '../assest/image2.png'
export {default as image3} from '../assest/image3.png'
export {default as Group9} from '../assest/Group 9.png'
export {default as Group6} from '../assest/Group 6.png'