export {default as packermover} from './packermover.png'
export {default as warehouse} from './warehouse.png'
export {default as move} from './move.png'
export {default as smiley} from './smiley.png'
export {default as people} from './people.png'
export {default as relocation} from './relocation.png'
export {default as group} from './Group.png'
export {default as star} from './star.png'