export  { default as Service} from '../assest/24-hours-support.png'
export  { default as logo} from '../assest/logo.png'
export  { default as schedule} from '../assest/schedule.png'
export  { default as warehouse} from '../assest/warehouse.png'
export  { default as train} from '../assest/train.png'
export  { default as exchange} from '../assest/exchange.png'
export  { default as delivery} from '../assest/delivery.png'
export  { default as canvas} from '../assest/canvas.png'
export  { default as briefcase} from '../assest/briefcase.png'
export  { default as customer} from '../assest/customer.png'
export  { default as quality} from '../assest/quality.png'
export  { default as premium} from '../assest/premium-quality.png'
export  { default as rating} from '../assest/rating.png'
export  { default as team} from '../assest/team.png'
export  { default as rectangle} from '../assest/Rectangle.png'
export  { default as group} from '../assest/Group.png'
export  { default as estimate} from '../assest/estimate.png'
export  { default as hours} from '../assest/24-hours.png'



export  { default as image5} from '../assest/slider/image5.png'
export  { default as image6} from '../assest/slider/image6.png'
export  { default as image7} from '../assest/slider/image7.png'
export  { default as image8} from '../assest/slider/image8.png'
export  { default as image9} from '../assest/slider/image9.png'
export  { default as image10} from '../assest/slider/image10.png'
export  { default as image11} from '../assest/slider/image11.png'
export  { default as image12} from '../assest/slider/image12.png'
export  { default as image13} from '../assest/slider/image13.png'